version: "3"
services:
  server:
    container_name: server
    build:
      context: ./backend
    ports:
      - "8080:8080"
  client:
    container_name: client
    build:
      context: ./frontend
    depends_on:
      - server
    ports:
      - "80:80"
